# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 更新 README.md

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      env:
        ACCESS_TOKEN: ${{ secrets.CREATE_README }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build

    - name: Record time
      run: echo `date` > date.log

    - name: Commit and push if changed   # 将README.md更新到仓库
      run: |
        git diff
        git config --global user.email "rliang.c@qq.com"
        git config --global user.name "ChenRiliang"
        git add -A
        git commit -m ":memo: Updated Readme" || exit 
        git push

    - name: done
      run: echo 'done'
